### ISSUE TITLE
fpsgraph shows warning missing parent

### ISSUE THREAD

**Issue by sunday00** [tweakpane/plugin-essentials#15]
- "tweakpane": "^3.1.4"
- "@tweakpane/plugin-essentials": "^0.1.7",
- "@tweakpane/core": "^1.1.4",

- expect : no waring
- current: showing browser console : "Missing 'parent' of BladeController in BladeRack.add. Please rebuild plugins with the latest core package."

```
import {Pane} from "tweakpane";
import * as EssentialsPlugin from '@tweakpane/plugin-essentials';

const gui = new Pane()

gui.registerPlugin(EssentialsPlugin);

export const guiFpsGraph = gui.addBlade({
  view: 'fpsgraph',
  label: 'FPS',
}

guiFpsGraph.begin()

renderer.render(scene, camera)
animate()

guiFpsGraph.end()
```

I want to know why console shows me this waring, and How to remove this waring.
Thanks for reading this issue.

**Comment by thiervoj** [comment]
I encountered the same warning using the same versions of tweakpane and @tweakpane/plugin-essentials

The plugin still seems to work anyways, it's just a console warning

**Comment by cocopon** [comment]
Tweakpane later 3.1.3 uses a new ViewProps structure and plugins need to rebuild with the latest core package. Plugins with the older core still work fine, but print warnings.

Please try the latest version 0.1.8.
