### ISSUE TITLE
Adding plugin inputs to a `TabPageApi`

### ISSUE THREAD

**Issue by FractalHQ** [tweakpane/plugin-essentials#16]
Is it possible to register plugins for a `TabPageApi`?  It seems the `TabPageApi` is *mostly* identical to the `FolderApi` but I haven't been able to add plugin inputs to it.

**Comment by cocopon** [comment]
Yes. You can add an input with a registered plugin like other containers (the root pane and folders):

```js
const pane = new Tweakpane.Pane();
pane.registerPlugin(TweakpaneEssentialsPlugin);

const t = pane.addTab({
  pages: [{title: 'foo'}, {title: 'bar'}],
});

// Add an interval input from the essentials plugin
t.pages[0].addInput({foo: {min: 0, max: 100}}, 'foo', {min: 0, max: 100});
```

**Comment by cocopon** [comment]
Feel free to reopen the issue if you have any updates.
