### ISSUE TITLE
fpsgraph plugin error

### ISSUE THREAD

**Issue by jkozniewski** [tweakpane/plugin-essentials#5]
Hi - first of all - thanks for such great control panel lib, all(?) other existing ones seem outdated and not really compelling.

Now the issue:
Creation of fps graph throws error - Uncaught TypeError: Cannot read properties of undefined (reading 'addBlade') 

No errors when adding cubic bezier (so plugin import / initialisation works in general)

code:
```
this.crtl = new Pane({
            title: 'Parameters',
            expanded: true,
        })
this.crtl.registerPlugin(EssentialsPlugin)

this.fpsGraph = this.ctrl.addBlade({
            view: 'fpsgraph',
            label: 'fpsgraph',
            lineCount: 2
 })
```

**Comment by cocopon** [comment]
Thank you for using Tweakpane. Please tell me details to reproduce the issue:

- Your environment (OS, Node.js, npm, browser, etc.)
- Library version (Tweakpane, plugins)
- How do you use the library (CDN, module bundler, language, etc.)

**Comment by jkozniewski** [comment]
environment - mac os 10.14.6, npm v6.14.13, nodejs v14.17.3, latest Chrome, parcel.js 2.0
lib version - tweakpane 3.0.5, @tweakpane/plugin-essentials 0.1.3
usage - ES6 modules (parcel.js 2.0 bundler), javascript

**Comment by jkozniewski** [comment]
Hi - any updates, can I somehow help to debug this further ?

**Comment by cocopon** [comment]
Sorry for the late reply due to other private projects. Could you create a minimum repository to reproduce the issue? I'm not a Parcel user.

**Comment by cocopon** [comment]
Sorry for the late reply due to other private projects. Could you create a minimum repository to reproduce the issue? I'm not a Parcel user.

**Comment by cocopon** [comment]
Feel free to reopen the issue if you get any updates.
